pyt_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('institution.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('scores/', include('scores.urls')),
    path('lookup/', include('lookup.urls')),
    path('quiz/', include('quiz.urls')),
    path('int_dev_env/', include('int_dev_env.urls', namespace='int_dev_env')),
    path('accounts/api/', include('accounts.api.urls', namespace='accounts-api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('<slug>/quizzes/', quiz_list, name='quiz_index'),
    path('progress/', view=QuizUserProgressView.as_view(), name='quiz_progress'),
    path('marking_list/', view=QuizMarkingList.as_view(), name='quiz_marking'),
    path('marking/<int:pk>/', view=QuizMarkingDetail.as_view(), name='quiz_marking_detail'),
    path('<int:pk>/<slug>/take/', view=QuizTake.as_view(), name='quiz_take'),
    path('<slug>/quiz_add/', QuizCreateView.as_view(), name='quiz_create'),
    path('<slug>/quiz_addition/', QuizCreateViewEssay.as_view(), name='quiz_create_essay'),
    path('<slug>/<int:pk>/add/', QuizUpdateView.as_view(), name='quiz_update'),
    path('<slug>/<int:pk>/delete/', quiz_delete, name='quiz_delete'),
    path('mc-question/add/<slug>/<int:quiz_id>/', MCQuestionCreate.as_view(), name='mc_create'),
    path('<slug>/essay_create/<int:quiz_id>/', EssayQuestionCreate.as_view(), name='essay_create'),
    path('<int:pk>/<slug:slug>/execute_code/', CodeExecutionView.as_view(), name='execute_code'),
    path('<int:course_pk>/<slug:quiz_slug>/quiz_completion/', quiz_completion, name='quiz_completion'),

]

quiz/models.py
import re
import json
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.validators import (MaxValueValidator, validate_comma_separated_integer_list,)
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import now
from django.conf import settings
from django.db.models.signals import pre_save
from django.db.models import Q
from model_utils.managers import InheritanceManager
from course.models import Course
from .utils import *


class QuizManager(models.Manager):
    def search(self, query=None):
        query_set = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(description__icontains=query)|
                         Q(category__icontains=query)|
                         Q(slug__icontains=query)
                        )
            query_set = query_set.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return query_set


CHOICE_ORDER_OPTIONS = (
    ('content', _('Content')),
    ('random', _('Random')),
    ('none', _('None'))
)

CATEGORY_OPTIONS = (
    ('assignment', _('Assignment')),)

CAT_OPT = (
    ('mcq', _('MCQ')),
    ('ess', _('ESS')),
)


class Quiz(models.Model):
    cat_q = models.CharField(max_length=20, choices=CAT_OPT, blank=True, verbose_name=_("Cat_q"))
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    title = models.CharField(verbose_name=_("Title"), max_length=60, blank=False)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, help_text=_("a description of the quiz"))
    category = models.TextField(choices=CATEGORY_OPTIONS, blank=True)
    timer = models.PositiveIntegerField(verbose_name=_("Timer for each Quiz Question (minutes)"), default=60)
    assignment_start_date = models.DateTimeField(verbose_name=_("Assignment Start Date"), null=True, blank=True)
    assignment_due_date = models.DateTimeField(verbose_name=_("Assignment Due Date"), null=True, blank=True)
    random_order = models.BooleanField(blank=False, default=False, verbose_name=_("Randomize"),
                                       help_text=_("Display the questions in a random order or as they are set?"))
    answers_at_end = models.BooleanField(blank=False, default=False, verbose_name=_("Show answers at the end"),
                                         help_text=_("Answers displayed at the end."))
    exam_paper = models.BooleanField(blank=False, default=False, verbose_name=_("Exam Paper"),
                                     help_text=_("Check to ensure assignment scores are saved"))
    single_attempt = models.BooleanField(blank=False, default=False, verbose_name=_("Single Attempt"),
                                         help_text=_("Single attempt allowed"))
    pass_mark = models.SmallIntegerField(blank=True, default=50, verbose_name=_("Pass Mark"),
                                         validators=[MaxValueValidator(100)],
                                         help_text=_("Minimum pass mark"))
    draft = models.BooleanField(blank=True, default=False, verbose_name=_("Draft"),
                                help_text=_("Quiz only available for lecturers and admin"))
    timestamp = models.DateTimeField(auto_now=True)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    objects = QuizManager()

    def get_essay_questions_count(self):
        count = Essay_Question.objects.filter(quiz=self).count()
        return count

    def save(self, force_insert=False, force_update=False, *args, **kwargs):

        if self.single_attempt is True:
            self.exam_paper = True
        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)
        if self.pass_mark < 0:
            raise ValidationError('%s is below 0' % self.pass_mark)
        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def get_absolute_url(self):
        return reverse('quiz_index', kwargs={'slug': self.course.slug})


def quiz_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(quiz_pre_save_receiver, sender=Quiz)


class ProgressManager(models.Manager):
    def new_progress(self, user):
        new_progress = self.create(user=user, score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    score = models.CharField(max_length=1024, verbose_name=_("Score"), validators=[validate_comma_separated_integer_list])
    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    def list_all_cat_scores(self):
        score_before = self.score
        output = {}
        if len(self.score) > len(score_before):
            self.save()
        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        if any([item is False for item in [score_to_add, possible_to_add, isinstance(score_to_add, int), isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")
        to_find = re.escape(str(question.quiz)) + r",(?P<score>\d+),(?P<possible>\d+),"
        match = re.search(to_find, self.score, re.IGNORECASE)
        if match:
            updated_score = int(match.group('score')) + abs(score_to_add)
            updated_possible = int(match.group('possible')) + abs(possible_to_add)
            new_score = ",".join([str(question.quiz), str(updated_score), str(updated_possible), ""])
            self.score = self.score.replace(match.group(), new_score)
            self.save()
        else:
            self.score += ",".join([str(question.quiz), str(score_to_add), str(possible_to_add), ""])
            self.save()

    def show_exams(self):
        if self.user.is_superuser:
            return Sitting.objects.filter(complete=True).order_by('-end')
        else:
            return Sitting.objects.filter(user=self.user, complete=True).order_by('-end')


class SittingManager(models.Manager):

    def new_sitting(self, user, quiz, course):
        if quiz.random_order is True:
            question_set = quiz.question_set.all().select_subclasses().order_by('?')
        else:
            question_set = quiz.question_set.all().select_subclasses()

        question_set = [item.id for item in question_set]

        if len(question_set) == 0:
            raise ImproperlyConfigured('Question set of the quiz is empty. Please configure questions properly')
        questions = ",".join(map(str, question_set)) + ","
        new_sitting = self.create(user=user, quiz=quiz, course=course, question_order=questions,
                                  question_list=questions, incorrect_questions="", current_score=0, complete=False,
                                  user_answers='{}')
        return new_sitting

    def user_sitting(self, user, quiz, course):
        if quiz.single_attempt is True and self.filter(user=user, quiz=quiz, course=course, complete=True).exists():
            return False
        try:
            sitting = self.get(user=user, quiz=quiz, course=course, complete=False)
        except Sitting.DoesNotExist:
            sitting = self.new_sitting(user, quiz, course)
        except Sitting.MultipleObjectsReturned:
            sitting = self.filter(user=user, quiz=quiz, course=course, complete=False)[0]
        return sitting


class Sitting(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"), on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, verbose_name=_("Quiz"), on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=True, verbose_name=_("Course"), on_delete=models.CASCADE)
    question_order = models.CharField(max_length=1024, verbose_name=_("Question Order"),
                                      validators=[validate_comma_separated_integer_list])
    question_list = models.CharField(max_length=1024, verbose_name=_("Question List"),
                                     validators=[validate_comma_separated_integer_list])
    incorrect_questions = models.CharField(max_length=1024, blank=True, verbose_name=_("Incorrect questions"),
                                           validators=[validate_comma_separated_integer_list])
    current_score = models.IntegerField(verbose_name=_("Current Score"))
    complete = models.BooleanField(default=False, blank=False, verbose_name=_("Complete"))
    user_answers = models.TextField(blank=True, default='{}', verbose_name=_("User Answers"))
    start = models.DateTimeField(auto_now_add=True, verbose_name=_("Start"))
    end = models.DateTimeField(null=True, blank=True, verbose_name=_("End"))
    objects = SittingManager()
    class Meta:
        permissions = (("view_sittings", _("Can see completed exams.")),)
    def get_first_question(self):
        if not self.question_list:
            return False
        first, _ = self.question_list.split(',', 1)
        question_id = int(first)
        return Question.objects.get_subclass(id=question_id)

    def remove_first_question(self):
        if not self.question_list:
            return
        _, others = self.question_list.split(',', 1)
        self.question_list = others
        self.save()

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.utils.translation import gettext_lazy as _
from django.db import transaction
from django.forms.models import inlineformset_factory
from accounts.models import User
from .models import *


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choices = [x for x in question.get_choices_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choices, widget=RadioSelect)


class EssayQuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayQuestionForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            label='Sandboxed IDE (RestrictedPython)',
            widget=Textarea(attrs={'style': 'width:100%', 'placeholder': 'Type Answer Here'}),
            required=False)


class EssayForm(forms.ModelForm):
    class Meta:
        model = Essay_Question  # Associate the form with the Essay_Question model
        fields = ['content', 'figure', 'explanation', 'expected_input', 'expected_output']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 7}),  # Set 'rows' attribute to 4
        }


class QuizAddForm(forms.ModelForm):

    class Meta:
        model = Quiz
        exclude = []
        widgets = {
            'assignment_start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'assignment_due_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    questions = forms.ModelMultipleChoiceField(
        queryset=Question.objects.all().select_subclasses(),
        required=False,
        label=_("Questions"),
        widget=FilteredSelectMultiple(
            verbose_name=_("Questions"),
            is_stacked=False))

    def __init__(self, *args, **kwargs):
        super(QuizAddForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['questions'].initial = self.instance.question_set.all().select_subclasses()

    def save(self, commit=True):
        quiz = super(QuizAddForm, self).save(commit=False)
        quiz.save()
        quiz.question_set.set(self.cleaned_data['questions'])
        self.save_m2m()
        return quiz


class MCQuestionForm(forms.ModelForm):
    class Meta:
        model = MCQuestion
        exclude = ()


MCQuestionFormSet = inlineformset_factory(
    MCQuestion, Choice, form=MCQuestionForm, fields=['choice', 'correct'], can_delete=True, extra=5)


# class CodeForm(forms.Form):
#     code = forms.CharField(widget=forms.Textarea(attrs={'style': 'width:100%'}))
#
#
# class SampleQuestionForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         # fields = ['text', 'answer']

templates/quiz/create_essay_quiz.html
{% extends 'Base_Sample.html' %}
{% block content %}
<h1>Create an Essay Quiz</h1>
<form method="post">
    {% csrf_token %}
    {{ form.title.label_tag }} {{ form.title }}
    {{ form.description.label_tag }} {{ form.description }}

    <!-- Add fields for essay questions here -->
    <h2>Essay Questions</h2>

    <div class="essay-question">
        {{ form.answers.label_tag }} {{ form.answers }}
    </div>

    <div class="essay-question">
        {{ form.answers.label_tag }} {{ form.answers }}
    </div>

    <input type="submit" value="Create Quiz">
</form>
{% endblock %}

templates/quiz/essay_question_form.html
{% extends 'Base_Sample.html' %}
{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i>
    <a href="{% url 'programs' %}" class="primary1"> Programs</a> <i>&rsaquo;</i>
    <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i>
    <a href="{{ course.get_absolute_url }}" class="primary1">{{ course }}</a> <i>&rsaquo;</i>
    <a href="{% url 'quiz_index' course.slug %}" class="primary1">Quiz list</a> <i>&rsaquo;</i> Essay Question add for {{ quiz_obj }}</div>

<div class="container">

    <div class="header-title-xl text-center mt-4">Questions form for {{ quiz_obj }}</div>
    <div class="title-line mb-5"></div>

    <div class="info-text bg-orange mb-3">{{ quizQuestions }} question added</div>

<form method="post">{% csrf_token %}
    {% if form.errors %}<p class="alert alert-danger">Correct the error(s) below.</p>{% endif %}
        <div class="row">
            <div class="col mx-3 py-4 border bg-white">
                <div class="form-group" hidden>
                    <label for="title">{{ form.quiz.label }}</label> {{ form.quiz }}
                    <span class="danger">{{ form.quiz.errors }}</span>
                    <small class="d-block text-muted">Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                </div>
                <div class="form-group">
                    <h6><label for="content">{{ form.content.label }}</label> {{ form.content }}</h6>
                    <span class="danger">{{ form.content.errors }}</span>
                    <small class="d-block text-muted">Enter the question text that you want displayed.</small>
                </div>
                <div class="form-group">
                    <h6><label for="figure">{{ form.figure.label }}</label> {{ form.figure }}</h6>
                    <span class="danger">{{ form.figure.errors }}</span>
                    <small class="d-block text-muted">Add an image for the question if it's necessary.</small>
                </div>
                <div class="form-group">
                    <h6><label for="explanation">{{ form.explanation.label }}</label> {{ form.explanation }}</h6>
                    <span class="danger">{{ form.explanation.errors }}</span>
                    <small class="d-block text-muted">Explanation to be shown after the question has been answered.</small>
                </div>
            </div>
            <div class="col mx-3 py-4 border bg-white">
                <div class="form-group">
                    <h6><label for="expected_input">{{ form.expected_input.label }}</label> {{ form.expected_input }}</h6>
                    <span class="danger">{{ form.expected_input.errors }}</span>
                    <small class="d-block text-muted">Enter the expected Code Input for this Question</small>
                </div>
                <div class="form-group">
                   <h6> <label for="expected_output">{{ form.expected_output.label }}</label> {{ form.expected_output }}</h6>
                    <span class="danger">{{ form.expected_output.errors }}</span>
                    <small class="d-block text-muted">Enter the expected Code Output for this question</small>
                </div>
            </div>
        </div>

    <center>
        <input type="submit" name="another" value="Submit and Add Another" class="btn btn-lg btn-primary my-4">
        <input type="submit" name="submit" value="Submit" class="btn btn-lg btn-outline-primary">
    </center>

</form>

</div>
{% endblock %}

templates/quiz/essay_quiz_take.html
{% extends 'base.html' %}

{% block content %}
  <h1>Essay Quiz: {{ quiz.title }}</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit Answer">
  </form>

  <p>Question {{ question.id }}:</p>
  <p>{{ question.content }}</p>

  <a href="{% url 'essay_quiz_take' course.slug quiz.pk %}">Next Question</a>
  <!-- Replace 'course.slug' and 'quiz.pk' with appropriate context variables -->

{% endblock %}

templates/quiz/mcquestion_form.html
{% extends 'Base_Sample.html' %}{% load i18n %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1"> Programs</a> <i>&rsaquo;</i> 
    <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
    <a href="{{ course.get_absolute_url }}" class="primary1">{{ course }}</a> <i>&rsaquo;</i> 
    <a href="{% url 'quiz_index' course.slug %}" class="primary1">Quiz list</a> <i>&rsaquo;</i> MC Question add for {{ quiz_obj }}</div>

<div class="container">

    <div class="header-title-xl text-center mt-4">Questions form for {{ quiz_obj }}</div>
    <div class="title-line mb-5"></div>

    <div class="info-text bg-orange mb-3">{{ quizQuestions }} question added</div>

    <form action="#" method="POST">{% csrf_token %}
        {% if form.errors %}<p class="alert alert-danger">Correct the error(s) below.</p>{% endif %}
        <div class="row">
            <div class="col mx-3 py-4 border bg-white">
                <div class="form-group" hidden>
                    <label for="title">{{ form.quiz.label }}</label> {{ form.quiz }}
                    <span class="danger">{{ form.quiz.errors }}</span>
                    <small class="d-block text-muted">Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                </div>
                <div class="form-group">
                    <h6><h6><label for="content">{{ form.content.label }}</label> {{ form.content }}</h6>
                    <span class="danger">{{ form.content.errors }}</span>
                    <small class="d-block text-muted">Enter the question text that you want displayed.</small>
                </div>
                <div class="form-group">
                    <h6><label for="figure">{{ form.figure.label }}</label> {{ form.figure }}</h6>
                    <span class="danger">{{ form.figure.errors }}</span>
                    <small class="d-block text-muted">Add an image for the question if it's necessary.</small>
                </div>
                <div class="form-group">
                    <h6><label for="explanation">{{ form.explanation.label }}</label> {{ form.explanation }}</h6>
                    <span class="danger">{{ form.explanation.errors }}</span>
                    <small class="d-block text-muted">Explanation to be shown after the question has been answered.</small>
                </div>
            </div>
            <div class="col mx-3 py-4 border bg-white">
                <div class="form-group">
                    <h6><label for="choice_order">{{ form.choice_order.label }}</label> {{ form.choice_order }}</h6>
                    <span class="danger">{{ form.choice_order.errors }}</span>
                    <small class="d-block text-muted">The order in which multichoice choice options are displayed to the user.</small>
                </div>
                <div class="border py-3">
                    <div class="lead text-center">Choices</div>
                {{ formset.management_form }}
                {% for fs in formset %}
                    <h6><label for="username">{{ fs.label }}</label></h6>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ fs.correct }} <small class="ml-1">Correct</small></span>
                        </div>
                        {{ fs.choice }}
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ fs.DELETE }} <small class="ml-1">Delete</small></span>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
        <center>
            <button type="submit" formnovalidate name="another" class="btn btn-lg btn-outline-primary">
                Save and add another
            </button>
            <button class="btn btn-lg btn-primary my-4" type="submit">Save</button>
        </center>
    </form>
</div>
{% endblock %}

templates/quiz/quiz_form.html
{% extends 'Base_Sample.html' %}{% load i18n %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> 
    <a href="{% url 'programs' %}" class="primary1"> Programs</a> <i>&rsaquo;</i> 
    <a href="{% url 'program_detail' course.program.id %}" class="primary1"> {{ course.program }}</a> <i>&rsaquo;</i> 
    <a href="{{ course.get_absolute_url }}" class="primary1">{{ course }}</a> <i>&rsaquo;</i> 
    <a href="{% url 'quiz_index' course.slug %}" class="primary1">Quizzes</a> <i>&rsaquo;</i> Add Quiz</div>

<div class="container">
    <div class="header-title-xl text-center">Quiz form for {{ course }}</div>
    <div class="title-line mb-5"></div>
    <form action="" method="POST">{% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="card p-2">
                    <div class="form-group" hidden>
                        <label for="course">{{ form.course.label }}</label><br> {{ form.course }}
                        <span class="danger">{{ form.course.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="category">{{ form.category.label }}</label> {{ form.category }}
                        <span class="danger">{{ form.category.errors }}</span>
                    </div>
                    <div class="form-group">
                        <label for="title">{{ form.title.label }}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="pass_mark">{{ form.pass_mark.label }}</label>
                        {{ form.pass_mark }}
                        <span class="danger">{{ form.pass_mark.errors }}</span>
                        <small class="d-block text-muted">Percentage required to pass exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="description">{{ form.description.label }}</label><br>
                        {{ form.description }}
                        <span class="danger">{{ form.description.errors }}</span>
                        <small class="d-block text-muted">a description of the quiz</small>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card p-3">
                    <div class="form-group" hidden>
                        <label for="questions">{{ form.questions.label }}</label><br> {{ form.questions }}
                        <span class="danger">{{ form.questions.errors }}</span>
                        <small class="d-block text-muted">Hold down "Control", or "Command" on a Mac, to select more than one.</small>
                    </div>
                    <div class="form-group">
                        <label for="assignment_due_date">{{ form.assignment_due_date.label }}</label><br> {{ form.assignment_due_date }}
                        <span class="danger">{{ form.assignment_due_date.errors }}</span>
                        <small class="d-block text-muted">Set the end date of the quiz.</small>
                    </div>
                    <div class="form-group">
                        <label for="assignment_start_date">{{ form.assignment_start_date.label }}</label><br> {{ form.assignment_start_date }}
                        <span class="danger">{{ form.assignment_start_date.errors }}</span>
                        <small class="d-block text-muted">Set the start date of the quiz.</small>
                    </div>
                    <div class="form-group">
                        <label for="timer">{{ form.timer.label }}</label><br> {{ form.timer }}
                        <span class="danger">{{ form.timer.errors }}</span>
                        <small class="d-block text-muted">Set the timer for this quiz, default is 60minutes.</small>
                    </div>
                    <div class="form-group">
                        <label for="random_order">{{ form.random_order.label }}</label>
                        {{ form.random_order }}
                        <span class="danger">{{ form.random_order.errors }}</span>
                        <small class="d-block text-muted">Display the questions in a random order or as they are set?</small>
                    </div>
                    <div class="form-group">
                        <label for="answers_at_end">{{ form.answers_at_end.label }}</label>
                        {{ form.answers_at_end }}
                        <span class="danger">{{ form.answers_at_end.errors }}</span>
                        <small class="d-block text-muted">Correct answer is NOT shown after question. Answers displayed at the end.</small>
                    </div>
                    <div class="form-group">
                        <label for="exam_paper">{{ form.exam_paper.label }}</label>
                        {{ form.exam_paper }}
                        <span class="danger">{{ form.exam_paper.errors }}</span>
                        <small class="d-block text-muted">If yes, the result of each attempt by a user will be stored. Necessary for marking.</small>
                    </div>
                    <div class="form-group">
                        <label for="single_attempt">{{ form.single_attempt.label }}</label>
                        {{ form.single_attempt }}
                        <!-- <input class="custom-checkbox" type="checkbox" name="single_attempt" id="id_single_attempt"> -->
                        <span class="danger">{{ form.single_attempt.errors }}</span>
                        <small class="d-block text-muted">If yes, only one attempt by a user will be permitted. Non users cannot sit this exam.</small>
                    </div>
                    <div class="form-group">
                        <label for="draft">{{ form.draft.label }}</label>
                        {{ form.draft }}
                        <span class="danger">{{ form.draft.errors }}</span>
                        <small class="d-block text-muted">If yes, the quiz is not displayed in the quiz list and can only be taken by users who can edit quizzes.</small>
                    </div>
                <!-- </div> -->
                </div>
            </div>
        </div>
        <center>
            <button class="btn btn-lg btn-primary my-4" id="{% if form.is_valid %}btn-transition{% endif %}" type="submit">Save & Continue</button>
        </center>
    </form>
</div>

{% endblock %}

templates/quiz/take_essay_quiz.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ quiz.title }}</h1>
<form method="post">
    {% csrf_token %}
    {% for question in questions %}
        <div>
            <p>{{ question.content }}</p>
            {{ form.answers }}
        </div>
    {% endfor %}
    <input type="submit" value="Submit Answers">
</form>
{% endblock %}