pyt_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('institution.urls')),
    path('accounts/', include('accounts.urls')),
    path('programs/', include('course.urls')),
    path('scores/', include('scores.urls')),
    path('lookup/', include('lookup.urls')),
    path('quiz/', include('quiz.urls')),
    path('int_dev_env/', include('int_dev_env.urls', namespace='int_dev_env')),
    path('accounts/api/', include('accounts.api.urls', namespace='accounts-api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('<slug>/quizzes/', quiz_list, name='quiz_index'),
    path('progress/', view=QuizUserProgressView.as_view(), name='quiz_progress'),
    path('marking_list/', view=QuizMarkingList.as_view(), name='quiz_marking'),
    path('marking/<int:pk>/', view=QuizMarkingDetail.as_view(), name='quiz_marking_detail'),
    path('<int:pk>/<slug>/take/', view=QuizTake.as_view(), name='quiz_take'),
    path('<slug>/quiz_add/', QuizCreateView.as_view(), name='quiz_create'),
    path('<slug>/quiz_addition/', QuizCreateViewEssay.as_view(), name='quiz_create_essay'),
    path('<slug>/<int:pk>/add/', QuizUpdateView.as_view(), name='quiz_update'),
    path('<slug>/<int:pk>/delete/', quiz_delete, name='quiz_delete'),
    path('mc-question/add/<slug>/<int:quiz_id>/', MCQuestionCreate.as_view(), name='mc_create'),
    path('<slug>/essay_create/<int:quiz_id>/', EssayQuestionCreate.as_view(), name='essay_create'),
    path('<int:pk>/<slug:slug>/execute_code/', CodeExecutionView.as_view(), name='execute_code'),
    path('<int:course_pk>/<slug:quiz_slug>/quiz_completion/', quiz_completion, name='quiz_completion'),

]

templates/Base_Question.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Python Tutorial</title>
    <link rel="stylesheet" href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/site.css' %}" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="stylesheet" href="font-awesome.css">
    <style>
        .hidden {
        display: none;
        }
        .navbar-nav li {
            border: 2px solid gold;
            border-radius: 12px;
            margin: 5px;
            padding: 12px;
            background-color: midnightblue;
            transition: all 0.3s ease-in-out;
            color: white;
        }

        .navbar-nav li:hover {
            border: 2px solid gold;
            box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.2);
            background-color: gold;
        }
        .navbar-nav li a {
            font-family: Arial, sans-serif;
            font-size: 18px;
            font-weight: bold;
        }

        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            color: #2c3e50;
        }

        h1 {
            color: #1abc9c;
            text-align: center;
            margin-top: 50px;
        }
        body {
            margin-bottom: 100px; /* Add margin to the bottom of the body equal to the height of the footer */
        }

        .dropdown {
          position: relative;
          display: inline-block;
        }

        .dropdown-content {
          display: none;
          position: absolute;
          background-color: midnightblue;
          min-width: 160px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
        }

        .dropdown-content a {
          color: white;
          padding: 12px;
          text-decoration: none;
          display: block;
        }

        .dropdown-content a:hover {
          background-color: gold;
          color: midnightblue;
        }

        .dropdown:hover .dropdown-content {
          display: block;
        }

        .capitalize {
            text-transform: capitalize;}

        .bars{
            position: absolute;
            top:80px;
            left: 0px;
            font-size: 1.5rem;
            background-color: midnightblue;
            color: grey;}

}
    </style>
</head>
<body>
    <header>
   <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0 mt-0 custom">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 28px; font-weight:bolder; color: gold; font-family:Arial, Helvetica, sans-serif">
            Python Tutorial
        </a>
        <ul class="navbar-nav flex-grow-1 justify-content-end">
                <li class="nav-item" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                    <span class="nav-link" style="color: white;">Welcome, {{ request.user.get_role }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}" style="color: white;">Logout</a>
                </li>
        </ul>
    </div>
    </nav>
    <nav class="navbar sticky-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mt-0 mb-0 flex-column">
    <div class="container mt-8">
    <form class="form-header" action="{% url 'query' %}" method="GET">
        <div class="input-group">
            <input id="primary-search" class="form-control form-control-xl" type="text" name="q" value="{{ request.GET.q }}"
                placeholder="Search for content here" required />
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"> Go </i>
                </button>
            </div>
        </div>
    </form>
    </div>
    <div class="container">
            <button id="toggleNavbarBtn" class="bars" ><div class="bars"><i class="fa fa-bars"></i></div></button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse flex-column">
            <ul class="navbar-nav flex-grow-1 justify-content-between">
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Dashboard</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'home' %}" style="font-size: 14px;">Home</a></div>
                </li>
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Courses and Programs</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'programs' %}" style="font-size: 14px;">Program</a>
                        {% if request.user.is_lecturer or request.user.is_student %}
                        <a href="{% url 'user_course_list' %}" style="font-size: 14px;">Courses</a>
                        {% endif %}
                        {% if request.user.is_student %}
                        <a href="{% url 'student_add_course' %}" style="font-size: 14px;">Add/Drop Course</a>
                        {% endif %}
                      </div>
                </li>
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Assessments</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        {% if request.user.is_lecturer %}
                        <a href="{% url 'quiz_marking' %}" style="font-size: 14px;">Complete Exams</a>
                        {% endif %}
                        <a href="{% url 'quiz_progress' %}" style="font-size: 14px;">Quiz Progress</a>
                      </div>
                </li>
                {% if request.user.is_lecturer or request.user.is_student %}
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Grades</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        {% if request.user.is_lecturer %}
                        <a href="{% url 'provisional_score' %}" style="font-size: 14px;">Manage Score</a>
                        {% endif %}
                        {% if request.user.is_student %}
                        <a href="{% url 'grade_results' %}" style="font-size: 14px;">Grade Results</a>
                        <a href="{% url 'ass_results' %}" style="font-size: 14px;">Assessment Results</a>
                        {% endif %}
                      </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}" style="color: white;">Analytics</a>
                </li>
                </li>
                {% if request.user.is_superuser %}
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Administration</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'session_list' %}" style="font-size: 14px;">Manage Session</a>
                        <a href="{% url 'trimester_list' %}" style="font-size: 14px;">Manage Trimester</a>
                        <a href="{% url 'view_allocated_course' %}" style="font-size: 14px;">Course Allocation</a>
                        <a href="{% url 'lecturer_list' %}" style="font-size: 14px;">Lecturers</a>
                        <a href="{% url 'student_list' %}" style="font-size: 14px;">Students</a>
                      </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'int_dev_env:execute_code' %}" style="color: white;">Python IDE</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    </header>

<div style="display: flex;">
   <nav id="sidebarMenu" style="width: 20%; background-color: midnightblue; padding: 20px;">
    <div class="text-center mb-3">
        <img class="profile-pic" src="{{ request.user.picture.url }}" style="max-width: 100%; height: auto;">
        <h3 class="text-body-secondary capitalize" style="color:white">{{ request.user.get_full_name }}</h3>
    </div>

    {% if request.user.is_lecturer or request.user.is_student %}
    <a class="btn btn-light btn-block mb-2" style="border: 1px solid gold;" href="{% url 'user_course_list' %}">
        <i class="fas fa-book"></i> My Courses
    </a>
    {% endif %}
    <a class="btn btn-light btn-block mb-2"style="border: 1px solid gold;" href="{% url 'profile' %}">
        <i class="fas fa-user"></i> Profile
    </a>

    <a class="btn btn-light btn-block mb-2" style="border: 1px solid gold;"href="{% url 'edit_profile' %}">
        <i class="fas fa-cogs"></i> Setting
    </a>
    <hr>
    <hr>
    <p class="text-muted text-center">
        Last login: {{ request.user.last_login|date }}</p>
    <hr>
    <hr>
</nav>

<div class="container" style="width: 80%;">
    <main role="main" class="pb-3">
        <div id="quiz-timer" class="text-center">
    <h3>Quiz Timer</h3>
    <div class="bg-light p-3 rounded">
        <span id="timer-minutes" class="display-4">00</span>:<span id="timer-seconds" class="display-4">00</span>
    </div>
</div>
        {% block content %}
        {% endblock %}
    </main>
</div>

</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row" style="margin-bottom:0;">
            </div>
            <div class="row">
            </div>
        </div>
    </footer>

    <script src="{% static 'lib/jquery/dist/jquery.min.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.bundle.min.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script src="{% static 'js/site.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script>
    const toggleNavbarBtn = document.getElementById('toggleNavbarBtn');
    const sidebarMenu = document.getElementById('sidebarMenu');

    // Retrieve the saved state from localStorage when the page loads
    const isNavbarHidden = localStorage.getItem('navbarHidden');
    if (isNavbarHidden === 'true') {
        sidebarMenu.classList.add('hidden');
    }

    toggleNavbarBtn.addEventListener('click', () => {
        sidebarMenu.classList.toggle('hidden');

        // Store the updated state in localStorage
        localStorage.setItem('navbarHidden', sidebarMenu.classList.contains('hidden'));
    });



function startTimer(duration) {
    var timer = duration, minutes, seconds;
    setInterval(function () {
        minutes = parseInt(timer / 60, 10);
        seconds = parseInt(timer % 60, 10);

        minutes = minutes < 10 ? "0" + minutes : minutes;
        seconds = seconds < 10 ? "0" + seconds : seconds;

        // Update only the text content of the timer elements
        document.getElementById("timer-minutes").textContent = minutes;
        document.getElementById("timer-seconds").textContent = seconds;

        if (--timer < 0) {
            clearInterval(countdown); // Stop the countdown
            document.getElementById("quiz-form").submit();
        }
    }, 1000);
}

document.addEventListener("DOMContentLoaded", function () {
    var timerDurationInSeconds = {{ quiz.timer }} * 60; // Convert minutes to seconds
    var display = document.querySelector("#quiz-timer");
    startTimer(timerDurationInSeconds, display);
});
</script>

</body>
</html>

templates/Base_Sample.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Python Tutorial</title>
    <link rel="stylesheet" href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/site.css' %}" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="stylesheet" href="font-awesome.css">
    <style>
        .hidden {
        display: none;
        }
        .navbar-nav li {
            border: 2px solid gold;
            border-radius: 12px;
            margin: 5px;
            padding: 12px;
            background-color: midnightblue;
            transition: all 0.3s ease-in-out;
            color: white;
        }

        .navbar-nav li:hover {
            border: 2px solid gold;
            box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.2);
            background-color: gold;
        }
        .navbar-nav li a {
            font-family: Arial, sans-serif;
            font-size: 18px;
            font-weight: bold;
        }

        body {
            font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
            color: #2c3e50;
        }

        h1 {
            color: #1abc9c;
            text-align: center;
            margin-top: 50px;
        }
        body {
            margin-bottom: 100px; /* Add margin to the bottom of the body equal to the height of the footer */
        }

        .dropdown {
          position: relative;
          display: inline-block;
        }

        .dropdown-content {
          display: none;
          position: absolute;
          background-color: midnightblue;
          min-width: 160px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
        }

        .dropdown-content a {
          color: white;
          padding: 12px;
          text-decoration: none;
          display: block;
        }

        .dropdown-content a:hover {
          background-color: gold;
          color: midnightblue;
        }

        .dropdown:hover .dropdown-content {
          display: block;
        }

        .capitalize {
            text-transform: capitalize;}

        .bars{
            position: absolute;
            top:80px;
            left: 0px;
            font-size: 1.5rem;
            background-color: midnightblue;
            color: grey;}

}
    </style>
</head>
<body>
    <header>
   <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0 mt-0 custom">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 28px; font-weight:bolder; color: gold; font-family:Arial, Helvetica, sans-serif">
            Python Tutorial
        </a>
        <ul class="navbar-nav flex-grow-1 justify-content-end">
                <li class="nav-item" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                    <span class="nav-link" style="color: white;">Welcome, {{ request.user.get_role }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}" style="color: white;">Logout</a>
                </li>
        </ul>
    </div>
    </nav>
    <nav class="navbar sticky-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mt-0 mb-0 flex-column">
    <div class="container mt-8">
    <form class="form-header" action="{% url 'query' %}" method="GET">
        <div class="input-group">
            <input id="primary-search" class="form-control form-control-xl" type="text" name="q" value="{{ request.GET.q }}"
                placeholder="Search for content here" required />
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search"> Go </i>
                </button>
            </div>
        </div>
    </form>
    </div>
    <div class="container">
            <button id="toggleNavbarBtn" class="bars" ><div class="bars"><i class="fa fa-bars"></i></div></button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse flex-column">
            <ul class="navbar-nav flex-grow-1 justify-content-between">
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Dashboard</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'home' %}" style="font-size: 14px;">Home</a></div>
                </li>
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Courses and Programs</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'programs' %}" style="font-size: 14px;">Program</a>
                        {% if request.user.is_lecturer or request.user.is_student %}
                        <a href="{% url 'user_course_list' %}" style="font-size: 14px;">Courses</a>
                        {% endif %}
                        {% if request.user.is_student %}
                        <a href="{% url 'student_add_course' %}" style="font-size: 14px;">Add/Drop Course</a>
                        {% endif %}
                      </div>
                </li>
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Assessments</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        {% if request.user.is_lecturer %}
                        <a href="{% url 'quiz_marking' %}" style="font-size: 14px;">Complete Exams</a>
                        {% endif %}
                        <a href="{% url 'quiz_progress' %}" style="font-size: 14px;">Quiz Progress</a>
                      </div>
                </li>
                {% if request.user.is_lecturer or request.user.is_student %}
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Grades</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        {% if request.user.is_lecturer %}
                        <a href="{% url 'provisional_score' %}" style="font-size: 14px;">Manage Score</a>
                        {% endif %}
                        {% if request.user.is_student %}
                        <a href="{% url 'grade_results' %}" style="font-size: 14px;">Grade Results</a>
                        <a href="{% url 'ass_results' %}" style="font-size: 14px;">Assessment Results</a>
                        {% endif %}
                      </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}" style="color: white;">Analytics</a>
                </li>
                </li>
                {% if request.user.is_superuser %}
                <li class="dropdown">
                    <a class="nav-link" style="color: white;">Administration</a>
                    <div class="dropdown-content" style="border: 2px solid gold; border-radius: 12px; margin: 5px; padding: 12px; background-color: midnightblue; color: white;">
                        <a href="{% url 'session_list' %}" style="font-size: 14px;">Manage Session</a>
                        <a href="{% url 'trimester_list' %}" style="font-size: 14px;">Manage Trimester</a>
                        <a href="{% url 'view_allocated_course' %}" style="font-size: 14px;">Course Allocation</a>
                        <a href="{% url 'lecturer_list' %}" style="font-size: 14px;">Lecturers</a>
                        <a href="{% url 'student_list' %}" style="font-size: 14px;">Students</a>
                      </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'int_dev_env:execute_code' %}" style="color: white;">Python IDE</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    </header>

<div style="display: flex;">
   <nav id="sidebarMenu" style="width: 20%; background-color: midnightblue; padding: 20px;">
    <div class="text-center mb-3">
        <img class="profile-pic" src="{{ request.user.picture.url }}" style="max-width: 100%; height: auto;">
        <h3 class="text-body-secondary capitalize" style="color:white">{{ request.user.get_full_name }}</h3>
    </div>

    {% if request.user.is_lecturer or request.user.is_student %}
    <a class="btn btn-light btn-block mb-2" style="border: 1px solid gold;" href="{% url 'user_course_list' %}">
        <i class="fas fa-book"></i> My Courses
    </a>
    {% endif %}
    <a class="btn btn-light btn-block mb-2"style="border: 1px solid gold;" href="{% url 'profile' %}">
        <i class="fas fa-user"></i> Profile
    </a>

    <a class="btn btn-light btn-block mb-2" style="border: 1px solid gold;"href="{% url 'edit_profile' %}">
        <i class="fas fa-cogs"></i> Setting
    </a>
    <hr>
    <hr>
    <p class="text-muted text-center">
        Last login: {{ request.user.last_login|date }}</p>
    <hr>
    <hr>
</nav>



<div class="container" style="width: 80%;">
    <main role="main" class="pb-3">
        {% block content %}
        {% endblock %}
    </main>
</div>

</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row" style="margin-bottom:0;">
            </div>
            <div class="row">
            </div>
        </div>
    </footer>

    <script src="{% static 'lib/jquery/dist/jquery.min.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.bundle.min.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script src="{% static 'js/site.js' %}?v={{ STATICFILES_VERSION }}"></script>
    <script>
    const toggleNavbarBtn = document.getElementById('toggleNavbarBtn');
    const sidebarMenu = document.getElementById('sidebarMenu');

    // Retrieve the saved state from localStorage when the page loads
    const isNavbarHidden = localStorage.getItem('navbarHidden');
    if (isNavbarHidden === 'true') {
        sidebarMenu.classList.add('hidden');
    }

    toggleNavbarBtn.addEventListener('click', () => {
        sidebarMenu.classList.toggle('hidden');

        // Store the updated state in localStorage
        localStorage.setItem('navbarHidden', sidebarMenu.classList.contains('hidden'));
    });
</script>

</body>
</html>

templates/correct_answer.html
{% load i18n %}
{% if previous.answers %}

  {% if user_was_incorrect %}
    <div class="alert alert-error">
  	  <strong>{% trans "You answered the above question incorrectly" %}</strong>
    </div>
  {% endif %}

  <table class="table table-striped table-bordered">
    <tbody>
  	  {% for answer in previous.answers %}
        {% if answer.correct %}
  	    <tr class="success">
  		  <td>{{ answer }}</td>
  		  <td><strong>{% trans "This is the correct answer" %}</strong></td>
        {% else %}
  		<tr>
      	  <td>{{ answer }}</td>
  		  <td>
  			{% if previous.question_type.MCQuestion %}
  			  {% if answer.id|add:"0" == previous.previous_answer|add:"0" %}
  			    {% trans "This was your answer." %}
  			  {% endif %}
  			{% endif %}
  		  </td>
  	  {% endif %}
  	    </tr>
  	{% endfor %}
    </tbody>
  </table>
{% endif %}

templates/execute_code1.html
{% extends "Base_Sample.html" %}
{% load i18n%}{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}
{% block content %}
<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a>

<div class="container">

    <div class="header-title-xl text-center">Online Integrated Development Environment</div>
    <div class="title-line mb-2"></div>

	<br />

	<p>
		<small class="muted">Practice Code</small>
		<strong>Practice</strong>
	</p>

	<div class="card">
		<div class="card-title lead bg-light p-2">Self Practice Coding Environment</div>
		<div class="card">
     <form method="post">Sandboxed IDE (RestrictedPython):
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-large btn-block btn-primary">Submit</button>
    </form>
			<br>
    <h2>Result:</h2>
    <pre>{{ result }}</pre>
    <h2>Output:</h2>
    <pre>{{ output }}</pre>
    <h2>Error:</h2>
    <pre>{{ error }}</pre>
		</div></div></div></div>
{% endblock %}

{% block js %}
<script>
const popupMessagesButtons = document.querySelectorAll('#popup-btn-messages');

for (const button of popupMessagesButtons) {
    button.addEventListener('click', () => {
        document.getElementById('popup-box-messages').style.display = 'none';
    })
}

</script>
{% endblock js %}

templates/progress.html
{% extends 'Base_Sample.html' %}
{% load i18n %}
{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Home</a> <i>&rsaquo;</i> Progress Page</div>

  {% if cat_scores %}

  <div class="header-title text-center">{% trans "Question Category Scores" %}</div>
  <div class="title-line"></div>

  <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
		<th>{% trans "Category" %}</th>
		<th>{% trans "Correctly answererd" %}</th>
		<th>{% trans "Incorrect" %}</th>
		<th>%</th>
	  </tr>
	</thead>

	<tbody>


	  {% for cat, value in cat_scores.items %}
	  <tr>
		<td>{{ cat }}</td>
		<td>{{ value.0 }}</td>
		<td>{{ value.1 }}</td>
		<td>{{ value.2 }}</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>


  {% endif %}

  {% if exams %}

  <hr>

  <div class="header-title-xl">{% trans "Previous exam papers" %}</div>
  <p class="lead text-muted">
	{% trans "Below are the results of exams that you have sat." %}
  </p>
  <div class="info-text bg-danger mb-2">Total complete exams: {{ exams_counter }}</div>
<div class="table-responsive">
  <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
		<th>#</th>
		<th>{% trans "Quiz Title" %}</th>
		<th>{% trans "Score" %}</th>
		<th>{% trans "Possible Score" %}</th>
		<th>Out of 100%</th>
	  </tr>
	</thead>

	<tbody>

	  {% for exam in exams %}

	  <tr>
		<td>{{ forloop.counter }}</td>
		<td>{{ exam.quiz.title }}</td>
		<td>{{ exam.current_score }}</td>
		<td>{{ exam.get_max_score }}</td>
		<td>{{ exam.get_percent_correct }}%</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>
</div>
  {% endif %}
  {% if not cat_scores and not exams %}
 	<div class="col-12 p-4 text-center"><h3><i class="far fa-frown"></i></h3> No recordes yet. to get a good recorde, try to do some quizzes in your course.</div> 
  {% endif %}

{% endblock %}